### ISSUE TITLE
Axe yeilds wood when digging dirt

### ISSUE THREAD

**Issue by NathanSalapat** [cx384/another_charcoal#3]
The axe can be used on dirt, leaves, sand, and other things, and always gives three split wood, you should probably add a check to see if the chopped item is in group:wood and then give the three split wood and if it isn't just let the node drop as usual.

**Comment by cx384** [comment]
OH I should fix that.
Thanks for this information.

**Comment by cx384** [comment]
Thanks to HybridDog now you can only get split wood from group:tree.
